import 'package:flutter/material.dart';
import 'package:technoed/models/tipos_dificuldade.dart';
import 'package:technoed/models/posicao.dart';
import 'package:technoed/models/forma.dart';
import 'package:technoed/models/tipos_forma.dart';

class Dificuldades {
  final levels = [
    TiposDificuldade([
      Forma(
        id: 1,
        height: 80,
        width: 160,
        targetPosition: Posicao(145, 2),
        position: Posicao(50, 400),
        color: Colors.red,
        targetColor: Colors.grey,
        shape: Triangulo(),
        rotationAngle: 225 / 360,
      ),
      Forma(
        id: 2,
        height: 30,
        width: 110,
        targetPosition: Posicao(93, 27),
        position: Posicao(50, 400),
        color: Colors.red,
        targetColor: Colors.grey,
        shape: Paralelograma(flip: true),
        rotationAngle: 45 / 360,
      ),
      Forma(
        id: 3,
        height: 42,
        width: 85,
        targetPosition: Posicao(148, 109),
        position: Posicao(50, 400),
        color: Colors.blue,
        targetColor: Colors.grey,
        shape: Triangulo(),
        rotationAngle: 45 / 360,
      ),
      Forma(
        id: 4,
        height: 80,
        width: 160,
        targetPosition: Posicao(75, 110),
        position: Posicao(50, 400),
        color: Colors.purple,
        targetColor: Colors.grey,
        shape: Triangulo(),
        rotationAngle: 0 / 360,
      ),
      Forma(
        id: 5,
        height: 60,
        width: 60,
        targetPosition: Posicao(154, 210.7),
        position: Posicao(50, 400),
        color: Colors.green,
        targetColor: Colors.grey,
        shape: Quadrado(),
        rotationAngle: 0 / 360,
      ),
      Forma(
        id: 6,
        height: 42,
        width: 85,
        targetPosition: Posicao(178, 269.5),
        position: Posicao(50, 400),
        color: Colors.yellow,
        targetColor: Colors.grey,
        shape: Triangulo(),
        rotationAngle: 135 / 360,
      ),
      Forma(
        id: 7,
        height: 57,
        width: 110,
        targetPosition: Posicao(127.5, 244),
        position: Posicao(50, 400),
        color: Colors.orange,
        targetColor: Colors.grey,
        shape: Triangulo(),
        rotationAngle: 90 / 360,
      ),
    ], 7),
    TiposDificuldade([
      Forma(
        id: 1,
        height: 30,
        width: 110,
        targetPosition: Posicao(165, 16),
        position: Posicao(50, 400),
        color: Colors.red,
        targetColor: Colors.redAccent,
        shape: Paralelograma(flip: false),
        rotationAngle: 45 / 360,
      ),
      Forma(
        id: 2,
        height: 80,
        width: 160,
        targetPosition: Posicao(201, 145),
        position: Posicao(50, 400),
        color: Colors.red,
        targetColor: Colors.redAccent,
        shape: Triangulo(),
        rotationAngle: 315 / 360,
      ),
      Forma(
        id: 3,
        height: 80,
        width: 160,
        targetPosition: Posicao(200, 85),
        position: Posicao(50, 400),
        color: Colors.purple,
        targetColor: Colors.purpleAccent,
        shape: Triangulo(),
        rotationAngle: 45 / 360,
      ),
      Forma(
        id: 4,
        height: 42,
        width: 85,
        targetPosition: Posicao(325, 137),
        position: Posicao(50, 400),
        color: Colors.orange,
        targetColor: Colors.orangeAccent,
        shape: Triangulo(),
        rotationAngle: 225 / 360,
      ),
      Forma(
        id: 5,
        height: 25,
        width: 50,
        targetPosition: Posicao(300, 202),
        position: Posicao(50, 400),
        color: Colors.blue,
        targetColor: Colors.blueAccent,
        shape: Triangulo(),
        rotationAngle: 0 / 360,
      ),
      Forma(
        id: 6,
        height: 60,
        width: 60,
        targetPosition: Posicao(150, 250),
        position: Posicao(50, 400),
        color: Colors.green,
        targetColor: Colors.greenAccent,
        shape: Quadrado(),
        rotationAngle: 0 / 360,
      ),
      Forma(
        id: 7,
        height: 42,
        width: 85,
        targetPosition: Posicao(105, 260),
        position: Posicao(50, 400),
        color: Colors.yellow,
        targetColor: Colors.yellowAccent,
        shape: Triangulo(),
        rotationAngle: 0 / 360,
      ),
    ], 7),
    TiposDificuldade([
      Forma(
        id: 1,
        height: 42,
        width: 85,
        targetPosition: Posicao(50, 137),
        position: Posicao(50, 400),
        color: Colors.orange,
        targetColor: Colors.orangeAccent,
        shape: Triangulo(),
        rotationAngle: 0 / 360,
      ),
      Forma(
        id: 2,
        height: 60,
        width: 60,
        targetPosition: Posicao(95, 150),
        position: Posicao(50, 400),
        color: Colors.green,
        targetColor: Colors.greenAccent,
        shape: Quadrado(),
        rotationAngle: 0 / 360,
      ),
      Forma(
        id: 3,
        height: 80,
        width: 160,
        targetPosition: Posicao(150, 27),
        position: Posicao(50, 400),
        color: Colors.purple,
        targetColor: Colors.purpleAccent,
        shape: Triangulo(),
        rotationAngle: 270 / 360,
      ),
      Forma(
        id: 4,
        height: 30,
        width: 110,
        targetPosition: Posicao(200, 110),
        position: Posicao(50, 400),
        color: Colors.red,
        targetColor: Colors.redAccent,
        shape: Paralelograma(flip: true),
        rotationAngle: 90 / 360,
      ),
      Forma(
        id: 5,
        height: 80,
        width: 160,
        targetPosition: Posicao(275, 50),
        position: Posicao(50, 400),
        color: Colors.red,
        targetColor: Colors.redAccent,
        shape: Triangulo(),
        rotationAngle: 225 / 360,
      ),
      Forma(
        id: 6,
        height: 35,
        width: 70,
        targetPosition: Posicao(365, 80),
        position: Posicao(50, 400),
        color: Colors.yellow,
        targetColor: Colors.yellowAccent,
        shape: Triangulo(),
        rotationAngle: 270 / 360,
      ),
      Forma(
        id: 7,
        height: 35,
        width: 70,
        targetPosition: Posicao(365, 150),
        position: Posicao(50, 400),
        color: Colors.blue,
        targetColor: Colors.blueAccent,
        shape: Triangulo(),
        rotationAngle: 270 / 360,
      ),
    ], 7),
    TiposDificuldade([
      Forma(
        id: 1,
        height: 42,
        width: 85,
        targetPosition: Posicao(50, 15),
        position: Posicao(50, 400),
        color: Colors.orange,
        targetColor: Colors.orangeAccent,
        shape: Triangulo(),
        rotationAngle: 0 / 360,
      ),
      Forma(
        id: 2,
        height: 60,
        width: 60,
        targetPosition: Posicao(95, 57),
        position: Posicao(50, 400),
        color: Colors.orange,
        targetColor: Colors.orangeAccent,
        shape: Quadrado(),
        rotationAngle: 0 / 360,
      ),
      Forma(
        id: 3,
        height: 80,
        width: 160,
        targetPosition: Posicao(145, 62),
        position: Posicao(50, 400),
        color: Colors.orange,
        targetColor: Colors.orangeAccent,
        shape: Triangulo(),
        rotationAngle: 45 / 360,
      ),
      Forma(
        id: 4,
        height: 42,
        width: 85,
        targetPosition: Posicao(230, 85),
        position: Posicao(50, 400),
        color: Colors.orange,
        targetColor: Colors.orangeAccent,
        shape: Triangulo(),
        rotationAngle: 0 / 360,
      ),
      Forma(
        id: 5,
        height: 80,
        width: 160,
        targetPosition: Posicao(105, 120),
        position: Posicao(50, 400),
        color: Colors.orange,
        targetColor: Colors.orangeAccent,
        shape: Triangulo(),
        rotationAngle: -45 / 360,
      ),
      Forma(
        id: 6,
        height: 30,
        width: 110,
        targetPosition: Posicao(155, 200),
        position: Posicao(50, 400),
        color: Colors.orange,
        targetColor: Colors.orangeAccent,
        shape: Paralelograma(flip: false),
        rotationAngle: -45 / 360,
      ),
      Forma(
        id: 7,
        height: 50,
        width: 100,
        targetPosition: Posicao(72, 215),
        position: Posicao(50, 400),
        color: Colors.orange,
        targetColor: Colors.orangeAccent,
        shape: Triangulo(),
        rotationAngle: 135 / 360,
      ),
    ], 7),
    TiposDificuldade([
      Forma(
        id: 1,
        height: 42,
        width: 85,
        targetPosition: Posicao(50, 15),
        position: Posicao(50, 400),
        color: Colors.orange,
        targetColor: Colors.orangeAccent,
        shape: Triangulo(),
        rotationAngle: 90 / 360,
      ),
      Forma(
        id: 2,
        height: 42,
        width: 85,
        targetPosition: Posicao(50, 60),
        position: Posicao(50, 400),
        color: Colors.orange,
        targetColor: Colors.orangeAccent,
        shape: Triangulo(),
        rotationAngle: 270 / 360,
      ),
      Forma(
        id: 3,
        height: 60,
        width: 60,
        targetPosition: Posicao(90, 50),
        position: Posicao(50, 400),
        color: Colors.orange,
        targetColor: Colors.orangeAccent,
        shape: Quadrado(),
        rotationAngle: 45 / 360,
      ),
      Forma(
        id: 4,
        height: 60,
        width: 120,
        targetPosition: Posicao(123, 65),
        position: Posicao(50, 400),
        color: Colors.orange,
        targetColor: Colors.orangeAccent,
        shape: Triangulo(),
        rotationAngle: 0 / 360,
      ),
      Forma(
        id: 5,
        height: 80,
        width: 160,
        targetPosition: Posicao(175, 15),
        position: Posicao(50, 400),
        color: Colors.orange,
        targetColor: Colors.orangeAccent,
        shape: Triangulo(),
        rotationAngle: -45 / 360,
      ),
      Forma(
        id: 6,
        height: 80,
        width: 160,
        targetPosition: Posicao(232, 75),
        position: Posicao(50, 400),
        color: Colors.orange,
        targetColor: Colors.orangeAccent,
        shape: Triangulo(),
        rotationAngle: 135 / 360,
      ),
      Forma(
        id: 7,
        height: 30,
        width: 110,
        targetPosition: Posicao(270, 185),
        position: Posicao(50, 400),
        color: Colors.orange,
        targetColor: Colors.orangeAccent,
        shape: Paralelograma(flip: false),
        rotationAngle: 0 / 360,
      ),
    ], 7),
    TiposDificuldade([
      Forma(
        id: 1,
        height: 50,
        width: 50,
        targetPosition: Posicao(50, 150),
        position: Posicao(50, 400),
        color: Colors.orange,
        targetColor: Colors.orangeAccent,
        shape: Quadrado(),
        rotationAngle: 25 / 360,
      ),
      Forma(
        id: 2,
        height: 80,
        width: 160,
        targetPosition: Posicao(100, 70),
        position: Posicao(50, 400),
        color: Colors.orange,
        targetColor: Colors.orangeAccent,
        shape: Triangulo(),
        rotationAngle: -45 / 360,
      ),
      Forma(
        id: 3,
        height: 30,
        width: 110,
        targetPosition: Posicao(150, 35),
        position: Posicao(50, 400),
        color: Colors.orange,
        targetColor: Colors.orangeAccent,
        shape: Paralelograma(flip: false),
        rotationAngle: -45 / 360,
      ),
      Forma(
        id: 4,
        height: 80,
        width: 160,
        targetPosition: Posicao(200, 85),
        position: Posicao(50, 400),
        color: Colors.orange,
        targetColor: Colors.orangeAccent,
        shape: Triangulo(),
        rotationAngle: 135 / 360,
      ),
      Forma(
        id: 5,
        height: 60,
        width: 120,
        targetPosition: Posicao(240, 165),
        position: Posicao(50, 400),
        color: Colors.orange,
        targetColor: Colors.orangeAccent,
        shape: Triangulo(),
        rotationAngle: 90 / 360,
      ),
      Forma(
        id: 6,
        height: 30,
        width: 60,
        targetPosition: Posicao(265, 17),
        position: Posicao(50, 400),
        color: Colors.orange,
        targetColor: Colors.orangeAccent,
        shape: Triangulo(),
        rotationAngle: -45 / 360,
      ),
      Forma(
        id: 7,
        height: 30,
        width: 60,
        targetPosition: Posicao(315, 147),
        position: Posicao(50, 400),
        color: Colors.orange,
        targetColor: Colors.orangeAccent,
        shape: Triangulo(),
        rotationAngle: 270 / 360,
      ),
    ], 7),
    TiposDificuldade([
      Forma(
        id: 1,
        height: 80,
        width: 160,
        targetPosition: Posicao(50, 15),
        position: Posicao(50, 400),
        color: Colors.orange,
        targetColor: Colors.orangeAccent,
        shape: Triangulo(),
        rotationAngle: -45 / 360,
      ),
      Forma(
        id: 2,
        height: 40,
        width: 80,
        targetPosition: Posicao(125, 90),
        position: Posicao(50, 400),
        color: Colors.orange,
        targetColor: Colors.orangeAccent,
        shape: Triangulo(),
        rotationAngle: 135 / 360,
      ),
      Forma(
        id: 3,
        height: 80,
        width: 160,
        targetPosition: Posicao(205, 35),
        position: Posicao(50, 400),
        color: Colors.orange,
        targetColor: Colors.orangeAccent,
        shape: Triangulo(),
        rotationAngle: -135 / 360,
      ),
      Forma(
        id: 4,
        height: 60,
        width: 120,
        targetPosition: Posicao(267, 25),
        position: Posicao(50, 400),
        color: Colors.orange,
        targetColor: Colors.orangeAccent,
        shape: Triangulo(),
        rotationAngle: -45 / 360,
      ),
      Forma(
        id: 5,
        height: 30,
        width: 110,
        targetPosition: Posicao(290, 90),
        position: Posicao(50, 400),
        color: Colors.orange,
        targetColor: Colors.orangeAccent,
        shape: Paralelograma(flip: true),
        rotationAngle: -45 / 360,
      ),
      Forma(
        id: 6,
        height: 50,
        width: 50,
        targetPosition: Posicao(335, 90),
        position: Posicao(50, 400),
        color: Colors.orange,
        targetColor: Colors.orangeAccent,
        shape: Quadrado(),
        rotationAngle: 0 / 360,
      ),
      Forma(
        id: 7,
        height: 40,
        width: 80,
        targetPosition: Posicao(410, 65),
        position: Posicao(50, 400),
        color: Colors.orange,
        targetColor: Colors.orangeAccent,
        shape: Triangulo(),
        rotationAngle: -135 / 360,
      ),
    ], 7),
    TiposDificuldade([
      Forma(
        id: 1,
        height: 80,
        width: 160,
        targetPosition: Posicao(50, 0),
        position: Posicao(50, 400),
        color: Colors.blue,
        targetColor: Colors.blueAccent,
        shape: Triangulo(),
        rotationAngle: -45 / 360,
      ),
      Forma(
        id: 2,
        height: 30,
        width: 60,
        targetPosition: Posicao(78, 124),
        position: Posicao(50, 400),
        color: Colors.blue,
        targetColor: Colors.blueAccent,
        shape: Triangulo(),
        rotationAngle: 135 / 360,
      ),
      Forma(
        id: 3,
        height: 80,
        width: 160,
        targetPosition: Posicao(50, 215),
        position: Posicao(50, 400),
        color: Colors.blue,
        targetColor: Colors.blueAccent,
        shape: Triangulo(),
        rotationAngle: 45 / 360,
      ),
      Forma(
        id: 4,
        height: 30,
        width: 60,
        targetPosition: Posicao(78, 192),
        position: Posicao(50, 400),
        color: Colors.blue,
        targetColor: Colors.blueAccent,
        shape: Triangulo(),
        rotationAngle: -135 / 360,
      ),
      Forma(
        id: 5,
        height: 50,
        width: 50,
        targetPosition: Posicao(61.5, 162),
        position: Posicao(50, 400),
        color: Colors.blue,
        targetColor: Colors.blueAccent,
        shape: Quadrado(),
        rotationAngle: 0 / 360,
      ),
      Forma(
        id: 6,
        height: 50,
        width: 50,
        targetPosition: Posicao(111, 162),
        position: Posicao(50, 400),
        color: Colors.blue,
        targetColor: Colors.blueAccent,
        shape: Quadrado(),
        rotationAngle: 0 / 360,
      ),
      Forma(
        id: 7,
        height: 50,
        width: 50,
        targetPosition: Posicao(160, 162),
        position: Posicao(50, 400),
        color: Colors.blue,
        targetColor: Colors.blueAccent,
        shape: Quadrado(),
        rotationAngle: 0 / 360,
      ),
      Forma(
        id: 8,
        height: 50,
        width: 50,
        targetPosition: Posicao(209, 162),
        position: Posicao(50, 400),
        color: Colors.blue,
        targetColor: Colors.blueAccent,
        shape: Quadrado(),
        rotationAngle: 0 / 360,
      ),
      Forma(
        id: 9,
        height: 50,
        width: 50,
        targetPosition: Posicao(258, 162),
        position: Posicao(50, 400),
        color: Colors.blue,
        targetColor: Colors.blueAccent,
        shape: Quadrado(),
        rotationAngle: 0 / 360,
      ),
    ], 9),
    TiposDificuldade([
      Forma(
        id: 1,
        height: 50,
        width: 50,
        targetPosition: Posicao(100, 250),
        position: Posicao(50, 400),
        color: Colors.purple,
        targetColor: Colors.purpleAccent,
        shape: Quadrado(),
        rotationAngle: -25 / 360,
      ),
      Forma(
        id: 2,
        height: 80,
        width: 160,
        targetPosition: Posicao(160, 150),
        position: Posicao(50, 400),
        color: Colors.purple,
        targetColor: Colors.purpleAccent,
        shape: Triangulo(),
        rotationAngle: -180 / 360,
      ),
      Forma(
        id: 3,
        height: 100,
        width: 200,
        targetPosition: Posicao(75, 0),
        position: Posicao(50, 400),
        color: Colors.purple,
        targetColor: Colors.purpleAccent,
        shape: Triangulo(),
        rotationAngle: -70 / 360,
      ),
      Forma(
        id: 4,
        height: 30,
        width: 110,
        targetPosition: Posicao(230, 190),
        position: Posicao(50, 400),
        color: Colors.purple,
        targetColor: Colors.purpleAccent,
        shape: Paralelograma(flip: false),
        rotationAngle: -45 / 360,
      ),
      Forma(
        id: 5,
        height: 40,
        width: 80,
        targetPosition: Posicao(288, 190),
        position: Posicao(50, 400),
        color: Colors.purple,
        targetColor: Colors.purpleAccent,
        shape: Triangulo(),
        rotationAngle: 135 / 360,
      ),
      Forma(
        id: 6,
        height: 40,
        width: 80,
        targetPosition: Posicao(260, 250),
        position: Posicao(50, 400),
        color: Colors.purple,
        targetColor: Colors.purpleAccent,
        shape: Triangulo(),
        rotationAngle: -270 / 360,
      ),
    ], 6),
  ];
}
